### ISSUE TITLE
Using ergonomock-function with addTypename true

### ISSUE THREAD

**Issue by jfulse** [SurveyMonkey/graphql-ergonomock#104]
Hello and thanks for a great library!

I'm trying to use `ergonomock()` together with a [`MockedProvider`](https://www.apollographql.com/docs/react/development-testing/testing/#the-mockedprovider-component) that uses `addTypename=true`. This doesn't work out of the box because the results from `ergonomock()` only includes `__typename` if the query does, and we would like to avoid adding it to the latter manually.

Is there any chance of an `addTypename` option to `ergonomock`? If not do you have a suggestion for another solution?

**Comment by joual** [comment]
Hey @jfulse !

I should be able to take a look at that relatively soon (within a couple days). Off the top of my head I don't see why we shouldn't be able to support that option. It actually sounds like a bug.

**Comment by jfulse** [comment]
Hello,

That's great news, thank you!

**Comment by victor-guoyu** [comment]
Hi @jfulse,

Could you please use the `ErgonoMockedProvider`  instead of the one from apollo react?

`import { ErgonoMockedProvider as MockedProvider } from "graphql-ergonomock";`

You can find an example here: https://github.com/SurveyMonkey/graphql-ergonomock/blob/master/README.md#basic-example-apollo

**Comment by jfulse** [comment]
Hello!

I did try that but couldn't get it working. I'll work in a minimal reproduction (and maybe this exercise itself indicate something incorrect in my setup..)

**Comment by jfulse** [comment]
Apologies! It seems our backend has added custom scalar types without me realising it and these are causing the issue. I assume there's a way to mock custom scalars and will dig in and find out. @victor-guoyu

**Comment by victor-guoyu** [comment]
@jfulse, thanks for the update and I don't think we have support for the custom scalar yet! 
I'll start working on it today and let you know when it's ready!

**Comment by jfulse** [comment]
> I'll start working on it today and let you know when it's ready!

Once again that's great news, thanks a lot!

**Comment by victor-guoyu** [comment]
👋 Hi, @jfulse, could you please update to the latest version  https://github.com/SurveyMonkey/graphql-ergonomock/releases/tag/v1.2.0

And here is an example of how you can provide a default mock function for the custom scalar type.

**Comment by jfulse** [comment]
It works with the latest version, thanks a lot for all the help and the new feature!
